//! Static Lua module graph and sandbox-local bundle emitter.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use super::{
    LuaConfig, LuaSourceMap, read_source, reject_section_markers, resolve_input, validate_relative,
};

pub(super) struct BundledLua {
    pub source: String,
    pub inputs: Vec<PathBuf>,
    pub sources: Vec<LuaSourceMap>,
}

#[derive(Debug)]
struct Module {
    name: String,
    path: PathBuf,
    source: String,
}

#[derive(Debug, Clone)]
struct Import {
    name: String,
    line: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Visit {
    Visiting,
    Complete,
}

pub(super) fn bundle(project_root: &Path, config: &LuaConfig) -> Result<BundledLua, String> {
    let lua_root = resolve_directory(project_root, &config.root, "lua.root")?;
    let entry_path = resolve_input(project_root, &config.entry, "lua.entry")?;
    if !entry_path.starts_with(&lua_root) {
        return Err(format!(
            "lua.entry {} must be inside lua.root {}",
            entry_path.display(),
            lua_root.display()
        ));
    }
    let entry_source = read_source(&entry_path, "Lua entry")?;
    reject_section_markers(&entry_source, &entry_path)?;
    validate_source_syntax(&entry_source, &entry_path, "<entry>", false)?;
    let entry_imports = scan_requires(&entry_source, &entry_path)?;

    let mut graph = Graph {
        project_root,
        lua_root: &lua_root,
        modules: BTreeMap::new(),
        visits: BTreeMap::new(),
        source_owners: BTreeMap::from([(entry_path.clone(), "<entry>".to_string())]),
    };
    let mut stack = Vec::new();
    for import in &entry_imports {
        graph.visit(&import.name, &entry_path, import.line, &mut stack)?;
    }

    let mut emitter = Emitter::new();
    emitter.line("-- generated by console build; edit project Lua sources, not this bundle");
    emitter.line("local require = (function()");
    emitter.line("local __console_factories = {}");
    emitter.line("local __console_loaded = {}");
    emitter.line("local __console_present = {}");
    emitter.line("local __console_loading = {}");
    emitter.line("local require");
    emitter.line("require = function(name)");
    emitter.line(
        "  if type(name) ~= 'string' then error('require expects a bundled module name', 2) end",
    );
    emitter.line("  if __console_present[name] then return __console_loaded[name] end");
    emitter.line("  local factory = __console_factories[name]");
    emitter.line(
        "  if factory == nil then error(\"module '\" .. name .. \"' was not bundled\", 2) end",
    );
    emitter.line("  if __console_loading[name] then error(\"circular require for module '\" .. name .. \"'\", 2) end");
    emitter.line("  __console_loading[name] = true");
    emitter.line("  local value = factory(name)");
    emitter.line("  __console_loading[name] = nil");
    emitter.line("  if value == nil then value = true end");
    emitter.line("  __console_present[name] = true");
    emitter.line("  __console_loaded[name] = value");
    emitter.line("  return value");
    emitter.line("end");

    let mut sources = Vec::new();
    for module in graph.modules.values() {
        emitter.line(&format!("-- console module: {}", module.name));
        emitter.line(&format!(
            "__console_factories[{}] = function(...)",
            lua_string(&module.name)
        ));
        let (generated_start_line, generated_end_line) = emitter.source(&module.source);
        emitter.line("end");
        sources.push(source_map(
            &module.name,
            &module.path,
            &module.source,
            generated_start_line,
            generated_end_line,
        ));
    }

    emitter.line("return require");
    emitter.line("end)()");

    emitter.line("-- console entry");
    let (generated_start_line, generated_end_line) = emitter.source(&entry_source);
    sources.push(source_map(
        "<entry>",
        &entry_path,
        &entry_source,
        generated_start_line,
        generated_end_line,
    ));

    let mut inputs = graph
        .modules
        .values()
        .map(|module| module.path.clone())
        .collect::<Vec<_>>();
    inputs.push(entry_path);
    inputs.sort();
    inputs.dedup();
    let source = emitter.finish();
    validate_syntax(&source, &sources)?;
    Ok(BundledLua {
        source,
        inputs,
        sources,
    })
}

struct Graph<'a> {
    project_root: &'a Path,
    lua_root: &'a Path,
    modules: BTreeMap<String, Module>,
    visits: BTreeMap<String, Visit>,
    source_owners: BTreeMap<PathBuf, String>,
}

impl Graph<'_> {
    fn visit(
        &mut self,
        name: &str,
        importer: &Path,
        import_line: usize,
        stack: &mut Vec<String>,
    ) -> Result<(), String> {
        validate_module_name(name, importer, import_line)?;
        match self.visits.get(name) {
            Some(Visit::Complete) => return Ok(()),
            Some(Visit::Visiting) => {
                let start = stack.iter().position(|item| item == name).unwrap_or(0);
                let mut cycle = stack[start..].to_vec();
                cycle.push(name.to_string());
                return Err(format!(
                    "{}:{} creates a Lua module cycle: {}",
                    importer.display(),
                    import_line,
                    cycle.join(" -> ")
                ));
            }
            None => {}
        }

        let relative = module_path(name);
        let path = resolve_input(
            self.project_root,
            &self.lua_root_relative(&relative),
            "Lua module",
        )
        .map_err(|error| {
            format!(
                "{}:{} cannot resolve module {name:?} at {}: {error}",
                importer.display(),
                import_line,
                self.lua_root.join(&relative).display()
            )
        })?;
        if !path.starts_with(self.lua_root) {
            return Err(format!(
                "{}:{} module {name:?} resolves outside lua.root {}",
                importer.display(),
                import_line,
                self.lua_root.display()
            ));
        }
        if let Some(owner) = self.source_owners.get(&path) {
            if owner != name {
                return Err(format!(
                    "{}:{} module {name:?} duplicates Lua source {} already owned by {owner:?}",
                    importer.display(),
                    import_line,
                    path.display()
                ));
            }
        } else {
            self.source_owners.insert(path.clone(), name.to_string());
        }

        let source = read_source(&path, &format!("Lua module {name:?}"))?;
        reject_section_markers(&source, &path)?;
        validate_source_syntax(&source, &path, name, true)?;
        let imports = scan_requires(&source, &path)?;
        self.visits.insert(name.to_string(), Visit::Visiting);
        stack.push(name.to_string());
        for import in imports {
            self.visit(&import.name, &path, import.line, stack)?;
        }
        stack.pop();
        self.visits.insert(name.to_string(), Visit::Complete);
        self.modules.insert(
            name.to_string(),
            Module {
                name: name.to_string(),
                path,
                source,
            },
        );
        Ok(())
    }

    fn lua_root_relative(&self, module: &Path) -> PathBuf {
        self.lua_root
            .strip_prefix(self.project_root)
            .expect("lua root was confined to project")
            .join(module)
    }
}

fn resolve_directory(root: &Path, relative: &Path, label: &str) -> Result<PathBuf, String> {
    validate_relative(relative, label)?;
    let unresolved = root.join(relative);
    let resolved = std::fs::canonicalize(&unresolved)
        .map_err(|error| format!("cannot open {label} {}: {error}", unresolved.display()))?;
    if !resolved.starts_with(root) {
        return Err(format!(
            "{label} {} escapes project root {}",
            unresolved.display(),
            root.display()
        ));
    }
    if !resolved.is_dir() {
        return Err(format!(
            "{label} {} is not a directory",
            unresolved.display()
        ));
    }
    Ok(resolved)
}

fn validate_module_name(name: &str, source: &Path, line: usize) -> Result<(), String> {
    let valid = !name.is_empty()
        && name.split('.').all(|segment| {
            !segment.is_empty()
                && segment
                    .chars()
                    .all(|character| character.is_ascii_alphanumeric() || character == '_')
        });
    if !valid {
        return Err(format!(
            "{}:{line} has invalid module name {name:?}; use dot-separated ASCII letters, digits, and underscores",
            source.display()
        ));
    }
    Ok(())
}

fn module_path(name: &str) -> PathBuf {
    let mut path = PathBuf::new();
    for segment in name.split('.') {
        path.push(segment);
    }
    path.set_extension("lua");
    path
}

fn source_map(
    module: &str,
    path: &Path,
    source: &str,
    generated_start_line: usize,
    generated_end_line: usize,
) -> LuaSourceMap {
    LuaSourceMap {
        module: module.to_string(),
        source: path.to_path_buf(),
        source_start_line: 1,
        source_end_line: source.lines().count().max(1),
        generated_start_line,
        generated_end_line,
    }
}

fn validate_syntax(source: &str, sources: &[LuaSourceMap]) -> Result<(), String> {
    let lua = console_core::mlua::Lua::new();
    if let Err(error) = lua
        .load(source)
        .set_name("@generated-cart.lua")
        .into_function()
    {
        let message = error.to_string();
        if let Some(generated_line) = syntax_error_line(&message)
            && let Some(mapping) = sources.iter().find(|mapping| {
                (mapping.generated_start_line..=mapping.generated_end_line)
                    .contains(&generated_line)
            })
        {
            let source_line = mapping.source_start_line
                + generated_line.saturating_sub(mapping.generated_start_line);
            return Err(format!(
                "Lua syntax error in {}:{source_line} (module {}, generated line {generated_line}): {message}",
                mapping.source.display(),
                mapping.module
            ));
        }
        return Err(format!(
            "generated Lua bundle has a syntax error: {message}"
        ));
    }
    Ok(())
}

fn validate_source_syntax(
    source: &str,
    path: &Path,
    module: &str,
    module_body: bool,
) -> Result<(), String> {
    // Modules execute as variadic factories in the generated bundle. Wrapping
    // each one independently preserves legal top-level `return`/`...` while
    // preventing malformed sources from consuming another factory's glue.
    let (candidate, line_offset) = if module_body {
        (format!("return function(...)\n{source}\nend"), 1)
    } else {
        (source.to_string(), 0)
    };
    let lua = console_core::mlua::Lua::new();
    if let Err(error) = lua
        .load(&candidate)
        .set_name("@console-source.lua")
        .into_function()
    {
        let message = error.to_string();
        let source_line = syntax_error_line_for(&message, "console-source.lua")
            .map(|line| line.saturating_sub(line_offset).max(1))
            .unwrap_or(1)
            .min(source.lines().count().max(1));
        return Err(format!(
            "Lua syntax error in {}:{source_line} (module {module}): {message}",
            path.display()
        ));
    }
    Ok(())
}

fn syntax_error_line(message: &str) -> Option<usize> {
    syntax_error_line_for(message, "generated-cart.lua")
}

fn syntax_error_line_for(message: &str, name: &str) -> Option<usize> {
    let marker = format!("{name}:");
    let start = message.find(&marker)? + marker.len();
    let digits = message[start..]
        .chars()
        .take_while(char::is_ascii_digit)
        .collect::<String>();
    (!digits.is_empty()).then(|| digits.parse().ok()).flatten()
}

fn lua_string(value: &str) -> String {
    format!("'{value}'")
}

struct Emitter {
    output: String,
    next_line: usize,
}

impl Emitter {
    fn new() -> Self {
        Self {
            output: String::new(),
            next_line: 1,
        }
    }

    fn line(&mut self, line: &str) {
        self.output.push_str(line);
        self.output.push('\n');
        self.next_line += 1;
    }

    fn source(&mut self, source: &str) -> (usize, usize) {
        let start = self.next_line;
        self.output.push_str(source);
        self.output.push('\n');
        let count = source.lines().count().max(1);
        self.next_line += count;
        (start, start + count - 1)
    }

    fn finish(mut self) -> String {
        self.output.pop();
        self.output
    }
}

fn scan_requires(source: &str, path: &Path) -> Result<Vec<Import>, String> {
    let bytes = source.as_bytes();
    let mut imports = Vec::new();
    let mut index = 0;
    let mut line = 1;
    let mut previous = None;
    while index < bytes.len() {
        if bytes[index].is_ascii_whitespace() {
            if bytes[index] == b'\n' {
                line += 1;
            }
            index += 1;
            continue;
        }
        if bytes[index..].starts_with(b"--") {
            let (next, next_line) = skip_comment(bytes, index, line, path)?;
            index = next;
            line = next_line;
            continue;
        }
        if matches!(bytes[index], b'\'' | b'"') {
            let (next, next_line) = skip_short_string(bytes, index, line, path)?;
            index = next;
            line = next_line;
            previous = Some(b's');
            continue;
        }
        if long_bracket_open(bytes, index).is_some() {
            let (next, next_line) = skip_long_string(bytes, index, line, path)?;
            index = next;
            line = next_line;
            previous = Some(b's');
            continue;
        }
        if bytes[index..].starts_with(b"..") {
            // Lua's concatenation (`..`) and vararg (`...`) tokens are not
            // member access. Consume the whole token so a following global
            // `require` remains visible to the dependency scanner.
            index += if bytes[index..].starts_with(b"...") {
                3
            } else {
                2
            };
            previous = Some(b'c');
            continue;
        }
        if bytes[index..].starts_with(b"::") {
            // A label delimiter is not a method-call colon. As with `..`,
            // consume it as one token so `::label:: require('module')` is
            // recognized as a global import.
            index += 2;
            previous = Some(b'c');
            continue;
        }
        if is_ident_start(bytes[index]) {
            let start = index;
            index += 1;
            while index < bytes.len() && is_ident_continue(bytes[index]) {
                index += 1;
            }
            let identifier = &source[start..index];
            if identifier.starts_with("__console_") {
                return Err(format!(
                    "{}:{line} uses reserved generated identifier {identifier:?}; names beginning __console_ are reserved",
                    path.display()
                ));
            }
            if identifier == "require" && !matches!(previous, Some(b'.' | b':')) {
                let require_line = line;
                let (import, next, next_line) =
                    parse_require(source, index, line, path, require_line)?;
                imports.push(import);
                index = next;
                line = next_line;
                previous = Some(b'c');
            } else {
                previous = Some(b'i');
            }
            continue;
        }
        previous = Some(bytes[index]);
        index += 1;
    }
    Ok(imports)
}

fn parse_require(
    source: &str,
    mut index: usize,
    mut line: usize,
    path: &Path,
    require_line: usize,
) -> Result<(Import, usize, usize), String> {
    let bytes = source.as_bytes();
    (index, line) = skip_trivia(bytes, index, line, path)?;
    let parenthesized = bytes.get(index) == Some(&b'(');
    if parenthesized {
        index += 1;
        (index, line) = skip_trivia(bytes, index, line, path)?;
    }
    let quote = bytes.get(index).copied();
    if !matches!(quote, Some(b'\'' | b'"')) {
        return Err(format!(
            "{}:{require_line} uses dynamic require; only require(\"foo.bar\") and require \"foo.bar\" are supported",
            path.display()
        ));
    }
    let quote = quote.expect("checked quote");
    let start = index + 1;
    index = start;
    while index < bytes.len() && bytes[index] != quote {
        if bytes[index] == b'\\' {
            return Err(format!(
                "{}:{require_line} module names cannot contain Lua escape sequences",
                path.display()
            ));
        }
        if bytes[index] == b'\n' {
            return Err(format!(
                "{}:{require_line} has an unterminated module string",
                path.display()
            ));
        }
        index += 1;
    }
    if index == bytes.len() {
        return Err(format!(
            "{}:{require_line} has an unterminated module string",
            path.display()
        ));
    }
    let name = source[start..index].to_string();
    index += 1;
    if parenthesized {
        (index, line) = skip_trivia(bytes, index, line, path)?;
        if bytes.get(index) != Some(&b')') {
            return Err(format!(
                "{}:{require_line} require must contain exactly one literal module name",
                path.display()
            ));
        }
        index += 1;
    }
    Ok((
        Import {
            name,
            line: require_line,
        },
        index,
        line,
    ))
}

fn skip_trivia(
    bytes: &[u8],
    mut index: usize,
    mut line: usize,
    path: &Path,
) -> Result<(usize, usize), String> {
    loop {
        while index < bytes.len() && bytes[index].is_ascii_whitespace() {
            if bytes[index] == b'\n' {
                line += 1;
            }
            index += 1;
        }
        if index < bytes.len() && bytes[index..].starts_with(b"--") {
            (index, line) = skip_comment(bytes, index, line, path)?;
        } else {
            return Ok((index, line));
        }
    }
}

fn skip_comment(
    bytes: &[u8],
    index: usize,
    line: usize,
    path: &Path,
) -> Result<(usize, usize), String> {
    let content = index + 2;
    if long_bracket_open(bytes, content).is_some() {
        return skip_long_string(bytes, content, line, path);
    }
    let mut next = content;
    while next < bytes.len() && bytes[next] != b'\n' {
        next += 1;
    }
    Ok((next, line))
}

fn skip_short_string(
    bytes: &[u8],
    mut index: usize,
    mut line: usize,
    path: &Path,
) -> Result<(usize, usize), String> {
    let quote = bytes[index];
    let start_line = line;
    index += 1;
    while index < bytes.len() {
        match bytes[index] {
            byte if byte == quote => return Ok((index + 1, line)),
            b'\\' => {
                index += 1;
                if bytes.get(index) == Some(&b'z') {
                    index += 1;
                    while index < bytes.len() && bytes[index].is_ascii_whitespace() {
                        if bytes[index] == b'\n' {
                            line += 1;
                        }
                        index += 1;
                    }
                } else {
                    if index < bytes.len() && bytes[index] == b'\n' {
                        line += 1;
                    }
                    index += usize::from(index < bytes.len());
                }
            }
            b'\n' => {
                return Err(format!(
                    "{}:{start_line} has an unterminated Lua string",
                    path.display()
                ));
            }
            _ => index += 1,
        }
    }
    Err(format!(
        "{}:{start_line} has an unterminated Lua string",
        path.display()
    ))
}

fn long_bracket_open(bytes: &[u8], index: usize) -> Option<(usize, usize)> {
    if bytes.get(index) != Some(&b'[') {
        return None;
    }
    let mut cursor = index + 1;
    while bytes.get(cursor) == Some(&b'=') {
        cursor += 1;
    }
    (bytes.get(cursor) == Some(&b'[')).then_some((cursor - index - 1, cursor + 1))
}

fn skip_long_string(
    bytes: &[u8],
    index: usize,
    mut line: usize,
    path: &Path,
) -> Result<(usize, usize), String> {
    let start_line = line;
    let (level, mut cursor) = long_bracket_open(bytes, index).expect("long bracket opener");
    while cursor < bytes.len() {
        if bytes[cursor] == b'\n' {
            line += 1;
            cursor += 1;
            continue;
        }
        if bytes[cursor] == b']' {
            let mut close = cursor + 1;
            for _ in 0..level {
                if bytes.get(close) != Some(&b'=') {
                    close = cursor + 1;
                    break;
                }
                close += 1;
            }
            if close == cursor + level + 1 && bytes.get(close) == Some(&b']') {
                return Ok((close + 1, line));
            }
        }
        cursor += 1;
    }
    Err(format!(
        "{}:{start_line} has an unterminated Lua long string or comment",
        path.display()
    ))
}

fn is_ident_start(byte: u8) -> bool {
    byte.is_ascii_alphabetic() || byte == b'_'
}

fn is_ident_continue(byte: u8) -> bool {
    is_ident_start(byte) || byte.is_ascii_digit()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scanner_finds_literal_calls_and_ignores_comments_strings_and_members() {
        let source = r#"
-- require("comment")
local text = "require('string')"
local long = [=[require("long")]=]
local a = require("alpha")
local b = require -- comment between tokens
  'nested.beta'
local c = "prefix" .. require("concatenated")
::again:: require("labeled")
local escaped = "joined\z
  string"
local d = require("after_escape")
object.require("member")
object:require("method")
"#;
        let imports = scan_requires(source, Path::new("main.lua")).unwrap();
        assert_eq!(
            imports
                .iter()
                .map(|import| (import.name.as_str(), import.line))
                .collect::<Vec<_>>(),
            vec![
                ("alpha", 5),
                ("nested.beta", 6),
                ("concatenated", 8),
                ("labeled", 9),
                ("after_escape", 12),
            ]
        );
    }

    #[test]
    fn scanner_rejects_dynamic_and_malformed_calls() {
        for source in [
            "require(name)",
            "require('a', 'b')",
            "local require = something",
            "function require(name) end",
            "require('escaped\\x2ename')",
            "local __console_factories = {}",
        ] {
            assert!(
                scan_requires(source, Path::new("main.lua")).is_err(),
                "accepted {source}"
            );
        }
    }

    #[test]
    fn module_paths_are_dot_separated_and_confined_by_grammar() {
        assert_eq!(module_path("game.player"), PathBuf::from("game/player.lua"));
        for invalid in ["", ".foo", "foo.", "foo..bar", "../foo", "foo/bar"] {
            assert!(validate_module_name(invalid, Path::new("main.lua"), 1).is_err());
        }
    }

    #[test]
    fn generated_syntax_lines_map_back_to_source_lines() {
        let mappings = vec![LuaSourceMap {
            module: "broken".into(),
            source: PathBuf::from("lua/broken.lua"),
            source_start_line: 1,
            source_end_line: 2,
            generated_start_line: 2,
            generated_end_line: 3,
        }];
        let error = validate_syntax("local wrapper = true\nlocal = nope\n", &mappings).unwrap_err();
        assert!(error.contains("lua/broken.lua:1"), "{error}");
        assert!(error.contains("module broken"), "{error}");
    }

    #[test]
    fn source_syntax_is_checked_in_its_actual_execution_context() {
        validate_source_syntax(
            "local name = ...\nreturn name",
            Path::new("lua/good.lua"),
            "good",
            true,
        )
        .unwrap();

        let error = validate_source_syntax(
            "if true then\n  return true",
            Path::new("lua/broken.lua"),
            "broken",
            true,
        )
        .unwrap_err();
        assert!(error.contains("lua/broken.lua:2"), "{error}");
        assert!(error.contains("module broken"), "{error}");
    }
}
